# 1. Habilita a interface web do banco H2
spring.h2.console.enabled=true

# 2. Define o caminho na URL para acessar o painel
spring.h2.console.path=/h2-console

# 3. Fixa o nome do banco de dados na memoria (mem)
# Se nao fizermos isso, o Spring gera um nome aleatorio
spring.datasource.url=jdbc:h2:mem:trajetoriadb

# 4. Credenciais padrao de acesso
spring.datasource.username=sa
spring.datasource.password=